USE [master]
GO

/****** Object:  Database [OOAD]    Script Date: 12/29/2017 11:31:55 PM ******/
CREATE DATABASE [OOAD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OOAD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.VIET\MSSQL\DATA\OOAD.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OOAD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.VIET\MSSQL\DATA\OOAD_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [OOAD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OOAD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OOAD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OOAD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OOAD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OOAD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OOAD] SET ARITHABORT OFF 
GO

ALTER DATABASE [OOAD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OOAD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OOAD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OOAD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OOAD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OOAD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OOAD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OOAD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OOAD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OOAD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OOAD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OOAD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OOAD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OOAD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OOAD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OOAD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OOAD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OOAD] SET RECOVERY FULL 
GO

ALTER DATABASE [OOAD] SET  MULTI_USER 
GO

ALTER DATABASE [OOAD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OOAD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OOAD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OOAD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OOAD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OOAD] SET  READ_WRITE 
GO

